var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
function Point(a,b){this.x=a;this.y=b;this.col=color(random(255),random(255),random(255));this.update=function(){this.x+=random(-1,1);this.y+=random(-1,1);this.x>width?this.x=1:0>this.x&&(this.x=width-1);this.y>height?this.y=1:0>this.y&&(this.y=height-1)};this.show=function(){point(this.x,this.y)}}
function Rectangle(a,b,c,d){this.x=a;this.y=b;this.w=c;this.h=d;this.contains=function(a){return a.pos.x>=this.x-this.w/2&&a.pos.x<=this.x+this.w/2&&a.pos.y>this.y-this.h/2&&a.pos.y<this.y+this.h/2};this.intersects=function(a){return!(a.x+a.w/2<this.x-this.w/2||a.y+a.h/2<this.y-this.h/2||a.x-a.w/2>this.x+this.w/2||a.y-a.h/2>this.y+this.h/2)}}
function Circle(a,b,c){this.x=a;this.y=b;this.r=c;this.contains=function(a){return dist(a.pos.x,a.pos.y,this.x,this.y)<this.r};this.intersects=function(a){var b=Math.abs(a.x-this.x),c=Math.abs(a.y-this.y),d=this.r,m=a.w;a=a.h;var n=dist(b,c,m,a);return b>d+m||c>d+a?!1:b<=m||c<=a?!0:n<=this.rSquared}}function QuadTree(a,b){this.boundary=a;this.capacity=b;this.points=[];this.divided=!1}
QuadTree.prototype.subdivice=function(){var a=this.boundary.x,b=this.boundary.y,c=this.boundary.w/2,d=this.boundary.h/2,f=new Rectangle(a-c/2,b-d/2,c,d),g=new Rectangle(a+c/2,b-d/2,c,d),k=new Rectangle(a-c/2,b+d/2,c,d);a=new Rectangle(a+c/2,b+d/2,c,d);this.topLeft=new QuadTree(f,this.capacity);this.topRight=new QuadTree(g,this.capacity);this.botLeft=new QuadTree(k,this.capacity);this.botRight=new QuadTree(a,this.capacity);this.divided=!0};
QuadTree.prototype.insert=function(a){if(!this.boundary.contains(a))return!1;if(this.points.length<this.capacity)return this.points.push(a),!0;this.divided||this.subdivice();return this.topLeft.insert(a)||this.topRight.insert(a)||this.botLeft.insert(a)||this.botRight.insert(a)?!0:!1};
QuadTree.prototype.query=function(a,b,c){b||(b=[]);if(!a.intersects(this.boundary))return b;for(var d=0;d<this.points.length;d++)if(a.contains(this.points[d])&&(b.push(this.points[d]),c))return b;this.divided&&(this.topLeft.query(a,b),this.topRight.query(a,b),this.botLeft.query(a,b),this.botRight.query(a,b));return b};QuadTree.prototype.clear=function(){this.points=[];this.divided&&(this.topLeft.clear(),this.topRight.clear(),this.botLeft.clear(),this.topRight.clear());this.divided=!1};
QuadTree.prototype.show=function(a){if("points at mouse"!=a){stroke(100);if("points"==a||"grid+points"==a){strokeWeight(4);for(var b=0;b<this.points.length;b++)this.points[b].show()}if("grid"==a||"grid+points"==a)noFill(),0<this.points.length?(stroke(255),strokeWeight(2)):strokeWeight(1),b=realToFake(this.boundary.x,this.boundary.y),rect(b.x,b.y,this.boundary.w,this.boundary.h);this.divided&&(this.topLeft.show(a),this.topRight.show(a),this.botLeft.show(a),this.botRight.show(a))}};
function GameMap(a,b,c){this.size=v(a,b);this.gridSize=c||200;this.hiddenMinimap=!1}GameMap.prototype.run=function(){this.drawGrid();this.drawEdge()};
GameMap.prototype.createMinimap=function(){this.minimapSize=250;this.offSetX=width-this.minimapSize-10;this.minimap?this.minimap.clear():this.minimap=createGraphics(this.minimapSize,this.minimapSize);this.minimap.fill(5,150);this.minimap.noStroke();this.minimap.rect(0,0,this.minimapSize,this.minimapSize);for(var a=$jscomp.makeIterator(wArr),b=a.next();!b.done;b=a.next())b=b.value,this.minimap.fill(b.col[0],b.col[1],b.col[2],100),this.circleToMinimap(b.pos,b.radius,!0);a=$jscomp.makeIterator(rArr);
for(b=a.next();!b.done;b=a.next())b=b.value,this.minimap.fill(b.col[0],b.col[1],b.col[2],200),this.circleToMinimap(b.pos,b.radius,!0);a=$jscomp.makeIterator(tArr);for(b=a.next();!b.done;b=a.next())b=b.value,this.minimap.fill(b.col[0],b.col[1],b.col[2],200),this.circleToMinimap(b.pos,b.radius,!0)};GameMap.prototype.convert=function(a,b){return b?map(a,0,this.minimapSize,0,this.size.x):map(a,0,this.size.x,0,this.minimapSize)};
GameMap.prototype.convertXY=function(a,b){return b?v(this.convert(a.x,!0),this.convert(a.y,!0)):v(this.convert(a.x),this.convert(a.y))};GameMap.prototype.circleToMinimap=function(a,b,c){a=this.convertXY(a);b=this.convert(b);c?this.minimap.ellipse(a.x,a.y,2*b,2*b):ellipse(a.x+this.offSetX,a.y+height-(this.minimapSize+10),2*b,2*b)};
GameMap.prototype.rectToMinimap=function(a,b,c){a=this.convertXY(a);b=this.convertXY(b);c?this.minimap.rect(a.x,a.y,b.x,b.y):rect(a.x+this.offSetX,a.y+height-(this.minimapSize+10),b.x,b.y)};
GameMap.prototype.showMinimap=function(){this.offSetX=this.hiddenMinimap?lerp(this.offSetX,width+10,.2):lerp(this.offSetX,width-this.minimapSize-10,.2);if(this.offSetX<width){image(this.minimap,this.offSetX,height-(this.minimapSize+10));strokeWeight(1);for(var a=$jscomp.makeIterator(pArr),b=a.next();!b.done;b=a.next())b=b.value,this.showPortals(b.inGate),b.outGate&&this.showPortals(b.outGate);a=$jscomp.makeIterator(redArr);for(b=a.next();!b.done;b=a.next())b=b.value,stroke(b.redValue,0,0),fill(b.redValue,
10,10,50),this.circleToMinimap(b.pos,b.radius,!1);stroke(255);noFill();this.circleToMinimap(viewport.target.pos,100,!1);this.rectToMinimap(viewport.pos,v(width,height),!1);mouseX>this.offSetX&&mouseY>height-this.minimapSize-10&&(keyIsDown(81)?(a=this.convertXY(v(mouseX,mouseY).sub(v(this.offSetX,height-this.minimapSize-10)),!0),viewport.pos=a):(textAlign(RIGHT),noStroke(),fill(150),text('hold "Q" to see',width-10,height-this.minimapSize-20)))}};
GameMap.prototype.showPortals=function(a){fill("out"==a.type?"orange":"blue");noStroke();this.circleToMinimap(a.pos,mil/4%150,!1);if(a.connectWith){var b=this.convertXY(a.pos).add(this.offSetX,height-(this.minimapSize+10));a=this.convertXY(a.connectWith.pos).add(this.offSetX,height-(this.minimapSize+10));stroke(200,50);line(b.x,b.y,a.x,a.y)}};
GameMap.prototype.drawEdge=function(){var a=v(0,0),b=v(this.size.x,0),c=v(0,this.size.y),d=v(this.size.x,this.size.y);stroke(255);strokeWeight(2);line(a.x,a.y,b.x,b.y);line(b.x,b.y,d.x,d.y);line(d.x,d.y,c.x,d.y);line(c.x,c.y,a.x,a.y)};
GameMap.prototype.drawGrid=function(){stroke(50,70);strokeWeight(3);for(var a=1,b=viewport.pos.x-width/2;b<viewport.pos.x+width/2;b+=a)0==floor(b)%this.gridSize&&(a=this.gridSize,line(b,viewport.pos.y-height/2,b,viewport.pos.y+height/2));a=1;for(b=viewport.pos.y-height/2;b<viewport.pos.y+height/2;b+=a)0==floor(b)%this.gridSize&&(a=this.gridSize,line(viewport.pos.x-width/2,b,viewport.pos.x+width/2,b))};
function Viewport(a){this.target=a||v(100,100);this.pos=a.pos.copy()||v(100,100);this.follow=!0;this.borderSize=25}Viewport.prototype.changeTarget=function(a){this.target=a};
Viewport.prototype.run=function(){if(this.follow&&!keyIsDown(81))this.pos=p5.Vector.lerp(this.pos,this.target.pos,.1);else if(mouseX>width-this.borderSize||mouseX<this.borderSize||mouseY>height-this.borderSize||mouseY<this.borderSize){var a=v(mouseX-width/2,mouseY-height/2).setMag(30);viewport.pos.add(a);noStroke();fill(200,20);25>mouseY&&rect(width/2,12.5,width,25);mouseY>height-25&&rect(width/2,height-12.5,width,25);25>mouseX&&rect(12.5,height/2,25,height);mouseX>width-25&&rect(width-12.5,height/
2,25,height)}};
var effects={force:function(a,b,c,d,f,g){g=[];var k=[],m=[];if(b.indexOf("bullet")){g=getBullets(c,d,f);for(var n=$jscomp.makeIterator(g),h=n.next();!h.done;h=n.next()){var l=h.value;p5.Vector.dist(l.pos,c)<l.info.radius+d&&(h="in"==a?p5.Vector.sub(c,l.pos):p5.Vector.sub(l.pos,c),l.vel.add(h.limit(l.info.speed)).limit(3*l.info.speed))}}if(b.indexOf("item"))for(k=getItems(c,d,f),n=$jscomp.makeIterator(k),h=n.next();!h.done;h=n.next())l=h.value,p5.Vector.dist(l.pos,c)<l.radius+d&&(h="in"==a?p5.Vector.sub(c,
l.pos):p5.Vector.sub(l.pos,c),l.vel.add(h.setMag(map(d+l.radius-h.mag(),0,d,1,10))));if(b.indexOf("item"))for(m=getPlayers(c,d,f),b=$jscomp.makeIterator(m),f=b.next();!f.done;f=b.next())f=f.value,p5.Vector.dist(f.pos,c)<f.radius+d&&(h="in"==a?p5.Vector.sub(c,f.pos):p5.Vector.sub(f.pos,c),f.vel.add(h.setMag(map(d+f.radius-h.mag(),0,d,1,f.vel.mag()))),f.nextPoint&&(f.nextPoint=null));return{bulls:g,items:k,players:m,all:m.concat(k).concat(g)}},explore:function(a,b,c,d){for(var f,g,k,m,n,h,l=0;l<b;l++)g=
random(5,10),h=25-g,f=v(random(-h,h),random(-h,h)),k=g/1.5,m=c||[random(255),random(255),random(255)],n=random(.1,.8),bArr.push(new Bullet(a,f,{name:"explore",damage:g,radius:k,speed:h,life:n,color:m},d));insideViewport({pos:a,radius:k})&&addSound("audio/"+random(["explosion_01","explosion_02"])+".mp3",!1,.5)},smoke:function(a,b,c,d,f,g){g=g||50;for(var k=0;k<c;k++)sArr.push(new Smoke(a+random(-g,g),b+random(-g,g),d,f))},collision:function(a,b,c,d){c=c||p5.Vector.dist(a.pos,b.pos);var f=.5*(c-a.radius-
(b.radius||b.info.radius));b.pos.x+=f*(a.pos.x-b.pos.x)/c;b.pos.y+=f*(a.pos.y-b.pos.y)/c;if(d&&b.info){d=(b.pos.x-a.pos.x)/c;a=(b.pos.y-a.pos.y)/c;c=-a;f=b.vel.x*c+b.vel.y*d;var g=b.vel.mag();b.vel.x=c*f+d*g*.7;b.vel.y=d*f+a*g*.7}}};
function Character(a,b,c,d,f,g){this.radius=30;this.name=a||RandomName[floor(random(RandomName.length))];this.pos=v(b,c);this.vel=v(0,0);this.col=d||[random(255),random(255),random(255)];this.health=f||random(100,300);this.score=10;this.killed=0;this.maxSpeed=4;this.healthShield=120;this.weaponBox=g?[0,1]:[0,1,2,3,4,5,6,7,8,9,10];this.weapon=clone(weapons[getValueAtIndex(weapons,this.weaponBox[floor(random(this.weaponBox.length))])]);this.weapon.gun=new Gun(this,this.weapon.gun);this.updateSize()}
Character.prototype.run=function(){this.weapon.gun.update();this.update();this.eat();collisionEdge(this,.6);insideViewport(this)&&this.show(this==p?fakeToReal(mouseX,mouseY):this.target);collisionBullets(this)};
Character.prototype.update=function(){this==p&&(150<(this.sLen||151)&&(this.sLen=1,addSound("audio/footstep_sand_01.mp3")),this.sLen+=this.vel.copy().mult(60/(fr+1)).mag());this.pos.add(this.vel.copy().mult(60/(fr+1)));this.vel.mult(.95);this.vel.limit(this.maxSpeed);this.shield&&this.makeShield();120>this.healthShield&&(this.healthShield+=60/(fr+1)*.1)};
Character.prototype.show=function(a){noStroke();fill(this.col[0],this.col[1],this.col[2]);a?drawPlayerWithShape(this,this.shield?"Circle":"Pentagon",p5.Vector.sub(a,this.pos).heading()):drawPlayerWithShape(this,this.shield?"Circle":"Pentagon",this.vel.heading());this.hide?fill(70):fill(200);textAlign(CENTER);text(floor(this.health)+(this.shield?" +"+floor(this.healthShield):""),this.pos.x,this.pos.y-this.radius-10);fill(90);text(this.name,this.pos.x,this.pos.y-this.radius-30)};
Character.prototype.eat=function(){var a=new Circle(this.pos.x,this.pos.y,this.radius+100);a=quadItems.query(a);a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b.value.eatBy(this)};
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
Character.prototype.makeShield=function(){var a=30+this.healthShield,b=getBullets(this.pos,a);if(b.length){b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=p5.Vector.dist(this.pos,c.pos);d<30+this.healthShield+c.info.radius&&(this.healthShield>=c.info.damage/5?this.healthShield-=c.info.damage/5:this.shield=!1,effects.collision({pos:this.pos,radius:a},c,d,!0))}}strokeWeight(1);stroke(70);fill(this.col[0],this.col[1],this.col[2],random(30,50));ellipse(this.pos.x,this.pos.y,
2*a,2*a)};
Character.prototype.die=function(a){var b=!1;a&&a.o&&(a.o.killed++,a.o.nextPoint=this.pos.copy(),b=a.o==this?!1:a.o);this==p?(addAlertBox("You was killed "+(b?"by "+b.name:"yourself"),"#f55","#fff"),b?addMessage(b.name+" has killed "+this.name+".","",!0):addMessage(this.name+" was died.","",!0),addMessage("You Died.","",!0,color(255,255,0)),p=null,setTimeout(function(){viewport.target=b?b:eArr[floor(random(eArr.length))];document.getElementById("resetBtn").style.display="block"},1500)):(b?addMessage(b.name+
" has killed "+this.name+".","",!0):addMessage(this.name+" was died.","",!0),this==viewport.target&&setTimeout(function(){viewport.target=b?b:eArr[floor(random(eArr.length))]},1500),eArr.splice(eArr.indexOf(this),1));for(a=0;a<Math.min(2,this.weaponBox.length);a++){var c=this.weaponBox[floor(random(this.weaponBox.length))];iArr.push(new Item(this.pos.x,this.pos.y,null,this.col,c))}for(a=0;a<random(this.score/2,this.score);a++)c=v(random(-1,1),random(-1,1)).setMag(random(1.5*this.score)),c=p5.Vector.add(this.pos,
c),iArr.push(new Item(c.x,c.y,null,this.col))};Character.prototype.move=function(){keyIsDown(87)&&this.vel.add(0,-1);keyIsDown(83)&&this.vel.add(0,1);keyIsDown(65)&&this.vel.add(-1,0);keyIsDown(68)&&this.vel.add(1,0);keyIsDown(38)&&this.vel.add(0,-1);keyIsDown(40)&&this.vel.add(0,1);keyIsDown(37)&&this.vel.add(-1,0);keyIsDown(39)&&this.vel.add(1,0)};Character.prototype.fire=function(a){this.shield||(0==this.weapon.gun.bullsLeft&&this!=p&&this.changeWeapon(1),this.weapon.gun.fire(a))};
Character.prototype.autoMove=function(){if(!this.nextPoint||p5.Vector.dist(this.pos,this.nextPoint)<this.radius){var a=getItems(this.pos,this.radius+width/2,!1,[],!0);if(0<a.length)this.nextPoint=a[floor(random(a.length))].pos;else{a=this.pos.x+random(-500,500);var b=this.pos.y+random(-500,500);a<this.radius?a=this.radius:a>gmap.size.x-this.radius&&(a=gmap.size.x-this.radius);b<this.radius?b=this.radius:b>gmap.size.y-this.radius&&(b=gmap.size.y-this.radius);this.nextPoint=v(a,b)}}else this.vel.mag()<
this.maxSpeed/1.2&&this.vel.add((this.nextPoint.x-this.pos.x)/4,(this.nextPoint.y-this.pos.y)/4).limit(this.maxSpeed)};
Character.prototype.autoFire=function(){this.target=null;if(30>this.health)this.shield=!0;else{this.shield=!1;var a=min(this.radius+width/2,this.radius+height/2),b=getPlayers(this.pos,a,[this]),c;b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())d=d.value,d.hide||p5.Vector.dist(this.pos,d.pos)<a+d.radius&&(c||(c=d));c&&(this.health>c.health?(a=c.radius+this.radius+150,b=p5.Vector.sub(this.pos,c.pos),this.nextPoint=c.pos.copy().add(b.setMag(a))):this.vel.add(p5.Vector.sub(this.pos,c.pos)).setMag(this.maxSpeed),
this.fire(c.pos.copy().add(10*c.vel.x,10*c.vel.y)),this.target=c.pos)}};Character.prototype.updateSize=function(){var a=.3*this.health;20<a&&600>a&&(this.radius=a)};Character.prototype.changeWeapon=function(a){a=this.weaponBox.indexOf(getObjectIndex(weapons,this.weapon.name))+a;a=0>a?this.weaponBox.length-1:a%this.weaponBox.length;this.changeWeaponTo(a)};
Character.prototype.changeWeaponTo=function(a){a%=this.weaponBox.length;this.weapon=clone(weapons[getValueAtIndex(weapons,this.weaponBox[a])]);this.weapon.gun=new Gun(this,this.weapon.gun)};Character.prototype.addWeapon=function(a){for(var b=!1,c=$jscomp.makeIterator(this.weaponBox),d=c.next();!d.done;d=c.next())if(a==d.value){b=!0;break}b||(this.weaponBox.push(a),this.changeWeaponTo(this.weaponBox.length-1));this==p&&addSound("audio/chest_pickup_01.mp3")};
function drawPlayerWithShape(a,b,c){switch(b){case "Circle":push();translate(a.pos.x,a.pos.y);rotate(c);fill(a.col);ellipse(0,0,2*a.radius,2*a.radius);fill(0);ellipse(a.radius/2,0,a.radius,a.radius/1.5*2);pop();break;case "Pentagon":push(),translate(a.pos.x,a.pos.y),b=a.vel.heading(),strokeWeight(1),rotate(b),stroke(255,180),fill(a.col),polygon(0,0,a.radius,5),stroke(30),strokeWeight(a.radius/2),point(a.radius/3*2,0),fill(0,200),stroke(150),strokeWeight(2),rotate(c-b),rect(a.radius/2,0,a.radius/1.5*
2,.4*a.radius),fill(0),ellipse(0,0,a.radius/3*2,a.radius/3*2),pop()}}function Gun(a,b){this.info=b;this.o=a;this.preShoot=0;this.bullsLeft=this.info.maxBulls}
Gun.prototype.fire=function(a){if(0<this.bullsLeft){if(!this.reloading&&mil-this.preShoot>=1E3*this.info.delay){for(var b=100-100*this.info.hitRatio,c,d,f=0;f<this.info.bullsPerTimes;f++)c=v(a.x-this.o.pos.x,a.y-this.o.pos.y).add(random(-b,b),random(-b,b)),d=c.copy().setMag(this.o.weapon.bullet.speed+(1<this.o.weapon.gun.info.bullsPerTimes?random(-2,2):0)),c=this.o.pos.copy().add(c.copy().setMag(this.o.radius+this.o.weapon.bullet.radius+5)),bArr.push(new Bullet(c,d,this.o.weapon.bullet,this.o));this.preShoot=
mil;this.bullsLeft--;this.o==p&&addSound(this.o.weapon.sound,!1,.4)}}else this.reload(),addSound("audio/empty_fire_01.mp3",!1,.7)};Gun.prototype.reload=function(){this.preShoot=mil+(this.info.maxBulls-this.bullsLeft)/this.info.maxBulls*this.info.reloadTime*1E3;this.bullsLeft=this.info.maxBulls;this.reloading=!0};Gun.prototype.update=function(){this.reloading&&mil>this.preShoot&&(this.reloading=!1,this.preShoot=mil-1E3*this.info.delay)};
function Bullet(a,b,c,d){this.info=c;this.pos=a.copy();this.vel=b;this.o=d;this.born=mil;this.col=this.info.color||[random(255),random(255),random(255)];this.info.whenfire&&this.info.whenfire(this)}Bullet.prototype.run=function(){this.update();insideViewport(this)&&this.show();this.info.working&&this.info.working(this);(mil-this.born)/1E3>this.info.life&&this.end()};Bullet.prototype.end=function(){this.info.finished&&this.info.finished(this);bArr.splice(bArr.indexOf(this),1)};
Bullet.prototype.update=function(){this.pos.add(this.vel.copy().mult(60/(fr+1)));collisionEdge(this,.99)};Bullet.prototype.show=function(){noStroke();fill(this.col[0],this.col[1],this.col[2],200);ellipse(this.pos.x,this.pos.y,2*this.info.radius)};function ExplorePoint(a,b,c,d,f,g){this.o=g;this.pos=v(a,b);this.num=c;this.col=d;this.timeCount=f;this.startTime=mil;this.radius=this.timeCount/10}
ExplorePoint.prototype.checkExplore=function(a){mil-this.startTime>=this.timeCount&&(effects.explore(this.pos,this.num,this.col,this.o),insideViewport(this)&&effects.force("out",["player","item"],this.pos,400),a.splice(a.indexOf(this),1))};ExplorePoint.prototype.show=function(){if(insideViewport(this)){var a=map(mil-this.startTime,0,this.timeCount,0,this.radius),b=map(a,0,this.radius,0,255);noStroke();fill(200,10,10,b);ellipse(this.pos.x,this.pos.y,this.radius-a)}};
function RedZone(a,b,c,d){this.pos=v(a,b);this.radius=c;this.ep=[];this.preDrop=mil;this.redRange=[120,255];this.redValue=random(120,255);this.grow=(this.redRange[1]-this.redRange[0])/50;this.born=mil;this.life=d}
RedZone.prototype.dropBoom=function(){if(mil-this.preDrop>1E5/this.radius){this.preDrop=mil;var a=v(random(-1,1),random(-1,1)).setMag(random(this.radius));a=p5.Vector.add(this.pos,a);this.ep.push(new ExplorePoint(a.x,a.y,random(10,20),[255,255,0],random(500,2E3)));.5<random(1)?iArr.push(new Item(a.x,a.y)):.9<random(1)&&bArr.push(new Bullet(a,v(0,0),bulletTypes.Mine))}};
RedZone.prototype.show=function(){this.redValue+=this.grow;if(this.redValue<=this.redRange[0]||this.redValue>=this.redRange[1])this.grow*=-1;if(insideViewport(this)){noStroke();fill(this.redValue,10,10,35);ellipse(this.pos.x,this.pos.y,2*this.radius);for(var a=this.ep.length-1;0<=a;a--)this.ep[a].show()}for(a=this.ep.length-1;0<=a;a--)this.ep[a].checkExplore(this.ep);mil-this.born>this.life?redArr.splice(redArr.indexOf(this),1):this.dropBoom()};
var gunTypes={Minigun:{maxBulls:100,delay:.1,reloadTime:2,bullsPerTimes:2,hitRatio:.6},AK:{maxBulls:30,delay:.125,reloadTime:1,bullsPerTimes:1,hitRatio:.9},Lazer:{maxBulls:35,delay:.2,reloadTime:1,bullsPerTimes:1,hitRatio:.9},Mine:{maxBulls:5,delay:.5,reloadTime:2,bullsPerTimes:1,hitRatio:1},Bazoka:{maxBulls:2,delay:1,reloadTime:2,bullsPerTimes:1,hitRatio:.9},Shotgun:{maxBulls:5,delay:.7,reloadTime:1.25,bullsPerTimes:5,hitRatio:.6},Portalgun:{maxBulls:2,delay:1,reloadTime:2,bullsPerTimes:1,hitRatio:1}},
bulletTypes={AK:{name:"AK",damage:3,radius:4,speed:20,life:1.5,color:[255,255,0]},Shotgun:{name:"Shotgun",damage:7,radius:5,speed:20,life:1.5,color:[200,255,10]},Minigun:{name:"Mini",damage:1,radius:3,speed:22,life:1,color:[255,255,0]},Bazoka:{name:"Bazoka",damage:1,radius:15,speed:14,life:5,color:[200,10,10],finished:function(a){effects.explore(a.pos,15,[255,255,0],a.o);effects.force("out",["player","item"],a.pos,400,[]);effects.smoke(a.pos.x,a.pos.y,3,600)},working:function(a){30<mil-(a.smoked||
1)&&(effects.smoke(a.pos.x,a.pos.y,1,200,random(10,30),15),a.smoked=mil)}},Mine:{name:"Mini",damage:5,radius:10,speed:.1,life:30,color:null,finished:function(a){epArr.push(new ExplorePoint(a.pos.x,a.pos.y,30,[255,100,50],400,a.o));setTimeout(function(){effects.smoke(a.pos.x,a.pos.y,4,1E3)},400)}},PortalBullet:{name:"PortalBullet",damage:0,radius:7,speed:12,life:5,color:[232,165,71],whenfire:function(a){a.forceType=random(["in","out"])},working:function(a){noStroke();effects.force(a.forceType,["player",
"item","bullet"],a.pos,100,[a,a.o]);"in"==a.forceType?fill(200,10,10,random(0,30)):fill(10,200,10,random(0,30));ellipse(a.pos.x,a.pos.y,150,150)},finished:function(a){for(var b=!1,c=pArr.length-1;0<=c;c--){var d=pArr[c];if(d.inGate.o==a.o&&!d.outGate){b=d;d.outGate=new Portal("out",a.pos.x,a.pos.y,null,null,10,a.o);d.inGate.connectWith=d.outGate;d.inGate.born=mil;effects.smoke(a.pos.x,a.pos.y,5,1500);break}}b||(a={inGate:new Portal("in",a.pos.x,a.pos.y,null,null,10,a.o),outGate:null},pArr.push(a))}},
RedzoneBullet:{name:"RedzoneBullet",damage:10,radius:15,speed:8,life:5,color:[255,150,30],working:function(a){effects.force("in",["player","item","bullet"],a.pos,(mil-a.born)/10,[a.o,a]);noStroke();fill(40,168,102,random(0,10));ellipse(a.pos.x,a.pos.y,(mil-a.born)/10,(mil-a.born)/10)},finished:function(a){effects.explore(a.pos,10,[200,200,0],a.o);redArr.push(new RedZone(a.pos.x,a.pos.y,(mil-a.born)/10,5E3));effects.smoke(a.pos.x,a.pos.y,3,600)}},Lazer:{name:"Lazer",damage:5,radius:3.5,speed:30,life:1,
color:[255,30,30],working:function(a){strokeWeight(7);stroke(255,30,30);beginShape();for(var b=0;3>b;b++)vertex(a.pos.x+a.vel.x*b,a.pos.y+a.vel.y*b);endShape(CLOSE)},finished:function(a){effects.smoke(a.pos.x,a.pos.y,1,200,5,!0)}},Bomp:{name:"Bomp",damage:0,radius:0,speed:100,life:0,color:null,whenfire:function(a){if(a.o==p){var b=fakeToReal(mouseX,mouseY);epArr.push(new ExplorePoint(b.x,b.y,20,[200,200,0],700,a.o));setTimeout(function(){effects.smoke(b.x,b.y,3,800);effects.force("out",["player",
"item"],b,400,[])},700)}}},Rocket:{name:"Rocket",damage:5,radius:10,speed:15,life:5,color:[200,10,10],working:function(a){if(a.target)a.vel=p5.Vector.lerp(a.vel,p5.Vector.sub(a.target.pos,a.pos).setMag(a.info.speed),.05),noFill(),strokeWeight(1),stroke(200,10,10),ellipse(a.target.pos.x,a.target.pos.y,2*a.target.radius+10);else{var b=getPlayers(a.pos,300,[a.o]);if(b.length){var c=null,d=300+maxSizeNow;b=$jscomp.makeIterator(b);for(var f=b.next();!f.done;f=b.next())if(f=f.value,!f.hide){var g=p5.Vector.dist(f.pos,
a.pos);g<d&&g<f.radius+300&&(d=g,c=f)}a.target=c}noFill();strokeWeight(3);stroke(100,random(100));ellipse(a.pos.x,a.pos.y,600)}30<mil-(a.smoked||1)&&(effects.smoke(a.pos.x,a.pos.y,1,200,random(10,30),15),a.smoked=mil)},finished:function(a){effects.explore(a.pos,15,[255,255,0],a.o);effects.force("out",["player","item"],a.pos,400,[]);effects.smoke(a.pos.x,a.pos.y,3,600)}},Turret:{name:"Turret",damage:10,radius:10,speed:1,life:10,color:[200,10,10],whenfire:function(a){a.preShoot=mil;a.shootCount=0;a.dir=
0},working:function(a){var b=getPlayers(a.pos,300,[a.o]);if(b.length){var c=null,d=300+maxSizeNow;b=$jscomp.makeIterator(b);for(var f=b.next();!f.done;f=b.next())if(f=f.value,!f.hide){var g=p5.Vector.dist(f.pos,a.pos);g<d&&g<f.radius+300&&(d=g,c=f)}a.target=c}else a.target=null;drawPlayerWithShape({pos:a.pos,vel:a.vel,radius:30,col:a.o.col},"Pentagon",a.dir);a.target?(noFill(),strokeWeight(1),stroke(200,10,10),ellipse(a.target.pos.x,a.target.pos.y,2*a.target.radius+10),line(a.pos.x,a.pos.y,a.target.pos.x,
a.target.pos.y),250<mil-a.preShoot&&(a.preShoot=mil,c=7==a.shootCount?bulletTypes.Bazoka:bulletTypes.Lazer,d=p5.Vector.sub(a.target.pos.copy().add(a.target.vel),a.pos),b=d.copy().setMag(c.speed),bArr.push(new Bullet(a.pos,b,c,a.o)),a.dir=d.heading(),a.shootCount+=7<=a.shootCount?-7:1)):(noFill(),stroke(100,random(100)),strokeWeight(2),ellipse(a.pos.x,a.pos.y,600))},finished:function(a){epArr.push(new ExplorePoint(a.pos.x,a.pos.y,20,[200,200,0],250,a.o));setTimeout(function(){effects.smoke(a.pos.x,
a.pos.y,3,1E3);effects.force("out",["player","item"],a.pos,400,[])},250)}}},weapons={AK:{name:"AK",gun:gunTypes.AK,bullet:bulletTypes.AK,sound:"audio/mp5_01.mp3"},Shotgun:{name:"Shotgun",gun:gunTypes.Shotgun,bullet:bulletTypes.Shotgun,sound:"audio/sv98_01.mp3"},Minigun:{name:"Minigun",gun:gunTypes.Minigun,bullet:bulletTypes.Minigun,sound:""},Mine:{name:"Mine",gun:gunTypes.Mine,bullet:bulletTypes.Mine,sound:""},Bazoka:{name:"Bazoka",gun:gunTypes.Bazoka,bullet:bulletTypes.Bazoka,sound:"audio/mosin_01.mp3"},
DropBomp:{name:"DropBomp",gun:gunTypes.Mine,bullet:bulletTypes.Bomp,sound:""},Lazer:{name:"Lazer",gun:gunTypes.Lazer,bullet:bulletTypes.Lazer,sound:""},PortalGun:{name:"PortalGun",gun:gunTypes.Portalgun,bullet:bulletTypes.PortalBullet,sound:""},RedzoneGun:{name:"RedzoneGun",gun:gunTypes.Bazoka,bullet:bulletTypes.RedzoneBullet,sound:""},Rocket:{name:"Rocket",gun:gunTypes.Bazoka,bullet:bulletTypes.Rocket,sound:""},Turret:{name:"Turret",gun:gunTypes.Bazoka,bullet:bulletTypes.Turret,sound:""}};
function Portal(a,b,c,d,f,g,k){this.o=k;this.type=a;this.pos=v(b,c);this.radius=f||100;this.connectWith=d;this.life=g||10;this.born=mil;this.grow=[];this.grow[0]=this.radius;this.grow[1]=this.radius/2}
Portal.prototype.update=function(){if("in"==this.type&&this.connectWith){var a=effects.force("in",["player","item","bullet"],this.pos,this.radius,[]);if(this.connectWith){a=$jscomp.makeIterator(a.all);for(var b=a.next();!b.done;b=a.next())b=b.value,p5.Vector.dist(this.pos,b.pos)<(b.radius||b.info.radius)&&(b.pos=this.connectWith.pos.copy())}}};Portal.prototype.run=function(){this.update();insideViewport(this)&&this.show();return this.end()};
Portal.prototype.end=function(){if((mil-this.born)/1E3>this.life)for(var a=0;a<pArr.length;a++){var b=pArr[a];if(this==b.inGate||this==b.outGate)return pArr.splice(a,1),!0}return!1};
Portal.prototype.show=function(){noStroke();"in"==this.type?fill(64,121,196,50):"out"==this.type&&fill(232,165,71,50);ellipse(this.pos.x,this.pos.y,1.5*this.radius,2*this.radius);for(var a=0;a<this.grow.length;a++)"in"==this.type&&this.connectWith?(this.grow[a]-=60/(fr+1)+random(-1,1),0>this.grow[a]&&(this.grow[a]=this.radius)):"out"==this.type&&(this.grow[a]+=60/(fr+1)+random(-1,1),this.grow[a]>this.radius&&(this.grow[a]=0));for(a=0;a<this.grow.length;a++)ellipse(this.pos.x,this.pos.y,1.5*this.grow[a],
2*this.grow[a])};function Smoke(a,b,c,d){this.pos=v(a,b);this.vel=v(0,0);this.radius=d||floor(random(10,50));this.born=mil;this.life=c}
Smoke.prototype.show=function(){if(insideViewport(this)){this.vel.add(random(-1,1),random(-1,1));this.pos.add(this.vel);this.vel.mult(.9);100>this.radius&&(this.radius+=random(7)*(30/(fr+1)));var a=map(this.life-(mil-this.born),0,this.life,30,255);fill(a,2*a);noStroke();ellipse(this.pos.x,this.pos.y,2*this.radius)}mil-this.born>this.life&&sArr.splice(sArr.indexOf(this),1)};
function InfoWeapon(){this.pos=v(0,height-10-25);this.size=v(100,50);this.show=function(){noStroke();this.pos.x=(gmap.offSetX||width)-this.size.x/2-20;fill(120,50);rect(this.pos.x,this.pos.y-.25*this.size.y,this.size.x,.5*this.size.y);fill(0,50);rect(this.pos.x,this.pos.y+.25*this.size.y,this.size.x,.5*this.size.y);noStroke();fill(255);textAlign(CENTER);viewport.target.shield?(mouseIsPressed&&fill(255,0,0),text("Shield On",this.pos.x,this.pos.y-.15*this.size.y)):(text(viewport.target.weapon.name,
this.pos.x,this.pos.y-.15*this.size.y),viewport.target.weapon.gun.reloading?(fill(255,150,20),text("..Reloading..",this.pos.x,this.pos.y+this.size.y/3)):text(viewport.target.weapon.gun.bullsLeft,this.pos.x,this.pos.y+.3*this.size.y))}}function Tree(a,b,c){this.pos=v(a,b);this.radius=c;this.col=[random(20),random(50,100),random(20)]}Tree.prototype.run=function(){insideViewport(this)&&this.show();this.update()};
Tree.prototype.update=function(){var a=getPlayers(this.pos,this.radius,[]);if(a.length){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,p5.Vector.dist(this.pos,b.pos)<this.radius-b.radius/2&&(b.vel.mult(.6),b.hide=!0)}a=getBullets(this.pos,this.radius,[]);if(a.length)for(a=$jscomp.makeIterator(a),b=a.next();!b.done;b=a.next())if(b=b.value,p5.Vector.dist(this.pos,b.pos)<this.radius+b.info.radius&&(b.end(),noStroke(),fill(this.col[0],this.col[1],this.col[2],60),ellipse(this.pos.x,
this.pos.y,2*this.radius),b.o&&(this.radius-=b.info.radius/2),20>this.radius)){this.end();break}};Tree.prototype.end=function(){insideViewport(this)&&addSound("audio/tree_break_01.mp3");if(.6<random(1)){var a=floor(random(getObjectLength(weapons)/2-1));iArr.push(new Item(this.pos.x,this.pos.y,null,this.col,a))}for(a=0;a<random(5,10);a++)iArr.push(new Item(this.pos.x+random(-30,30),this.pos.y+random(-30,30)));tArr.splice(tArr.indexOf(this),1)};
Tree.prototype.show=function(){fill(this.col[0],this.col[1],this.col[2],252);noStroke();ellipse(this.pos.x,this.pos.y,2*this.radius+100*ampLevel)};function Rock(a,b,c){this.pos=v(a,b);this.radius=c;a=floor(random(30,70));this.col=[a,a,a]}Rock.prototype.run=function(){insideViewport(this)&&this.show();this.update()};
Rock.prototype.update=function(){var a=getBullets(this.pos,this.radius,[]);if(a.length){var b=$jscomp.makeIterator(a);for(a=b.next();!a.done;a=b.next()){var c=a.value;a=p5.Vector.dist(this.pos,c.pos);if(a<this.radius+c.info.radius&&(effects.collision(this,c,a,!0),noStroke(),fill(this.col[0],this.col[1],this.col[2],60),ellipse(this.pos.x,this.pos.y,2*this.radius),c.o&&(this.radius-=c.info.radius/4),20>this.radius)){this.end();break}}}a=getPlayers(this.pos,this.radius,[]);if(a.length)for(b=$jscomp.makeIterator(a),
a=b.next();!a.done;a=b.next())c=a.value,a=p5.Vector.dist(this.pos,c.pos),a<this.radius+c.radius&&(effects.collision(this,c,a),c.nextPoint&&(c.nextPoint=v(c.pos.x+random(-300,300),c.pos.y+random(-300,300))));a=getItems(this.pos,this.radius,[]);if(a.length)for(b=$jscomp.makeIterator(a),a=b.next();!a.done;a=b.next())c=a.value,a=p5.Vector.dist(this.pos,c.pos),a<this.radius+c.radius&&effects.collision(this,c,a)};
Rock.prototype.end=function(){var a=getObjectLength(weapons);a=floor(random(a/2-1,a));iArr.push(new Item(this.pos.x,this.pos.y,null,this.col,a));for(a=0;a<random(10,20);a++)iArr.push(new Item(this.pos.x+random(-30,30),this.pos.y+random(-30,30)));rArr.splice(rArr.indexOf(this),1)};Rock.prototype.show=function(){fill(this.col[0],this.col[1],this.col[2]);stroke(70);strokeWeight(1);ellipse(this.pos.x,this.pos.y,2*this.radius)};
function Item(a,b,c,d,f){this.pos=v(a,b);this.vel=v(0,0);this.radius=c||random(5,15);this.col=d||[random(255),random(255),random(255)];this.born=mil;this.life=random(6E4,3E5);this.dropGun=f;isNaN(this.dropGun)||(this.nameGun=getValueAtIndex(weapons,f))}Item.prototype.run=function(){insideViewport(this)&&(this.update(),this.show());isNaN(this.dropGun)&&mil-this.born>this.life&&iArr.splice(iArr.indexOf(this),1)};
Item.prototype.eatBy=function(a){var b=p5.Vector.dist(this.pos,a.pos);b<a.radius?(iArr.splice(iArr.indexOf(this),1),a.health+=this.radius/5,a.score+=this.radius/10,this.dropGun&&a.addWeapon(this.dropGun),a.updateSize()):this.vel=v(a.pos.x-this.pos.x,a.pos.y-this.pos.y).setMag(250/(b-a.radius)).limit(15)};Item.prototype.update=function(){this.pos.add(random(-2,2),random(-2,2));this.pos.add(this.vel);this.vel.mult(.8);collisionEdge(this,1)};
Item.prototype.show=function(){this.nameGun?(fill(10),stroke(255,150),ellipse(this.pos.x,this.pos.y,30),noStroke(),fill(255),text(this.nameGun,this.pos.x,this.pos.y)):(noStroke(),fill(this.col[0],this.col[1],this.col[2],50),ellipse(this.pos.x,this.pos.y,2*this.radius),fill(this.col[0],this.col[1],this.col[2],150),ellipse(this.pos.x,this.pos.y,1.5*this.radius),fill(this.col[0],this.col[1],this.col[2],255),ellipse(this.pos.x,this.pos.y,this.radius))};
function Notification(a,b,c,d){this.textInside=a;this.size=b||20;this.col=c||[255,255,255,170];this.life=d;this.born=mil;this.run=function(){if(mil-this.born<this.life){var a=notifi.indexOf(this)*(this.size+10)+30;textAlign(CENTER);textSize(this.size);noStroke();fill(this.col[0],this.col[1],this.col[2],170);text(this.textInside,width/2,a)}else notifi.splice(notifi.indexOf(this),1)}}
function Water(a,b,c){this.pos=v(a,b);this.radius=c||random(50,400);this.col=[21,53,117];this.preRipple=mil;this.delay=800;this.ripple=[]}Water.prototype.run=function(){this.show()};Water.prototype.show=function(){noStroke();fill(this.col[0],this.col[1],this.col[2],150);ellipse(this.pos.x,this.pos.y,2*this.radius);this.trackPlayer();this.showRipple()};
Water.prototype.trackPlayer=function(){var a=getPlayers(this.pos,this.radius,[]);if(a.length){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,p5.Vector.dist(this.pos,b.pos)<this.radius-b.radius/2&&(b.vel.mag()>b.maxSpeed/2&&mil-this.preRipple>this.delay&&(this.ripple.push({x:b.pos.x,y:b.pos.y,r:10}),this.preRipple=mil,b==p&&addSound("audio/footstep_water_02.mp3")),b.vel.mult(.65))}a=getBullets(this.pos,this.radius,[]);if(a.length)for(a=$jscomp.makeIterator(a),b=a.next();!b.done;b=
a.next())b=b.value,p5.Vector.dist(this.pos,b.pos)<this.radius-b.info.radius/2&&b.vel.mult(.9)};Water.prototype.showRipple=function(){for(var a=this.ripple.length-1;0<=a;a--){var b=this.ripple[a];fill(150,10);stroke(150,200-2*b.r);strokeWeight(2);ellipse(b.x,b.y,2*b.r);b.r+=60/(fr+1);255<2*b.r&&this.ripple.splice(a,1)}};
var RandomName="Jacob;William;Ethan;Daniel;Logan;God Of God;Matthew;Lucas;Jackson;David;Samuel;Dont Kill Me;Luke;Henry;Andrew;Nathan;Huong;Nhien;Nhung;Huynh;Dat;Dinh;Hanh;Ros;Tay;Thanh;Hue;Nang;Mua;Bao;Tam;FuckYou;Dem;Sang;Cute;Dude;Kiss;Hope;Car;God;Fake;Alan;Hoi;Diem;Master;Be Friend or Die;Yi;Yasuo;Irela;Vi;Lux;Sion;Doctor;U r mine;Jinx;Jhin;Roma;Computer;Fax;Plane;Sky;Head;Tree;Lake;Water;Fire;Snow;Mountain;Dog;Cat;Bird;Snack;Candy;Huu;Noah;Mason;Hoang;Hien;Linh;Nam;Tam;Hau;Foria;Hoa;Thao;Trang;Thuy;Huan;Luong;Test Game;Hao;Thuan;Nga;Huy;Hang;An;Anh;Call me;Thien;Ngan;<3;Love;Michael;Seclo;Play Alone;Heo;Julia;Jame;Thomson;LOL;Ris;Tris;Nhan;Dang;Dam".split(";"),musics=
{SongList:[{name:"DEEP HOUSE SUMMER MIX 2 - AHMET KILIC - Ahmet Kilic",link:"https://api.soundcloud.com/tracks/143041228/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"Sea Wave Sound - Nature Sound - Beach Bums",link:"https://api.soundcloud.com/tracks/200099207/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"Relaxation Music Sleeping - Rain and Thunder (1 hours) - ELIRT",link:"https://api.soundcloud.com/tracks/146823529/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"Relaxing Rain and Loud Thunder - R.J. Stefanski",
link:"https://api.soundcloud.com/tracks/52301001/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"Relaxing Rain and Thunder Sound , Sleep Meditation - Ibne Waheedi",link:"https://api.soundcloud.com/tracks/110697958/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"30 Minute Deep Sleep Music - T Mega",link:"https://api.soundcloud.com/tracks/237317520/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"RELAX \u2013 relaxdaily N\u00b0048 - relaxdaily",link:"https://api.soundcloud.com/tracks/49267945/stream?client_id=587aa2d384f7333a886010d5f52f302a"},
{name:"Smooth jazz music - JWilborn",link:"https://api.soundcloud.com/tracks/58735518/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"As she passes - Levi Patel",link:"https://api.soundcloud.com/tracks/191576787/stream?client_id=587aa2d384f7333a886010d5f52f302a"},{name:"Matt Simons - Catch & Release (Deepend Remix)",link:"https://api.soundcloud.com/tracks/194510401/stream?client_id=587aa2d384f7333a886010d5f52f302a"}]};
function reset(){eArr=[];bArr=[];iArr=[];rArr=[];tArr=[];pArr=[];redArr=[];epArr=[];sArr=[];wArr=[];notifi=[];p=new Character(pname,random(gmap.size.x),random(gmap.size.y),null,100,"isP");effects.smoke(p.pos.x,p.pos.y,5,700,30);pcol=p.col;viewport=new Viewport(p);for(var a=0;a<maxE;a++)eArr.push(new Character(null,random(gmap.size.x),random(gmap.size.y)));for(a=0;a<maxRock;a++)rArr.push(new Rock(random(gmap.size.x),random(gmap.size.y),random(50,300)));for(a=0;a<maxTree;a++)tArr.push(new Tree(random(gmap.size.x),
random(gmap.size.y),random(50,150)));for(a=0;a<maxWater;a++)wArr.push(new Water(random(gmap.size.x),random(gmap.size.y),random(400,1E3)));gmap.createMinimap()}function realToFake(a,b){return v(width/2+a-viewport.pos.x,height/2+b-viewport.pos.y)}function fakeToReal(a,b){return v(a-width/2+viewport.pos.x,b-height/2+viewport.pos.y)}
function collisionBullets(a){var b=new Circle(a.pos.x,a.pos.y,a.radius+50),c=quadBulls.query(b);b=!1;if(c.length){c=$jscomp.makeIterator(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,p5.Vector.dist(a.pos,d.pos)<a.radius+d.info.radius){a.health-=d.info.damage;a.updateSize();b=!0;var f=d;d.end()}b&&a.nextPoint&&(a.nextPoint=null);b&&(b=2*a.radius+30,fill(255,0,0,120),ellipse(a.pos.x,a.pos.y,b,b));0>a.health&&a.die(f)}}
function collisionEdge(a,b){var c=a.radius||a.info.radius,d=gmap.size.y-c,f=gmap.size.x-c;a.pos.y<c?(a.vel.y*=-b,a.pos.y=c):a.pos.y>d&&(a.vel.y*=-b,a.pos.y=d);a.pos.x<c?(a.vel.x*=-b,a.pos.x=c):a.pos.x>f&&(a.vel.x*=-b,a.pos.x=f)}function insideViewport(a){var b=a.pos;a=a.radius||a.info.radius;return b.x>viewport.pos.x-width/2-a&&b.x<viewport.pos.x+width/2+a&&b.y>viewport.pos.y-height/2-a&&b.y<viewport.pos.y+height/2+a}
function polygon(a,b,c,d){d=TWO_PI/d;beginShape();for(var f=0;f<TWO_PI;f+=d){var g=a+cos(f)*c,k=b+sin(f)*c;vertex(g,k)}endShape(CLOSE)}function prettyTime(a){a=a||0;var b=a%60|0,c=a/60%60|0;return(a=a/3600|0)?a+":"+("0"+c).substr(-2)+":"+("0"+b).substr(-2):c+":"+("0"+b).substr(-2)}function v(a,b){return createVector(a,b)}
function createNewAudio(a){null==myAudio?(myAudio=createAudio(a),myAudio.elt.controls=!0,myAudio.elt.volume=.5,myAudio.autoplay(!0),myAudio.onended(function(a){changeSong(1)}),myAudio.elt.onloadeddata=function(){myAudio.elt.currentTime=random(myAudio.elt.duration)},myAudio.connect(p5.soundOut)):myAudio.src=a}
function changeSong(a){songNow+=a;songNow>=musics.SongList.length?songNow=0:0>songNow&&(songNow=musics.SongList.length-1);notifi.push(new Notification("Song: "+musics.SongList[songNow].name,20,null,5E3));createNewAudio(musics.SongList[songNow].link)}function addSound(a,b,c){}function addAlertBox(a,b,c){var d=document.getElementById("alert");d.childNodes[0].nodeValue=a;d.style.backgroundColor=b;d.style.opacity=.7;d.style.zIndex=2;c&&(d.style.color=c)}
function addMessage(a,b,c,d,f){var g=document.createElement("p");d&&(g.style.backgroundColor="rgba("+d.levels[0]+","+d.levels[1]+","+d.levels[2]+",0.3)");c&&(d=document.createElement("span"),d.textContent=c?prettyTime(mil/1E3)+"  ":"",g.appendChild(d));b&&(c=document.createElement("span"),c.style.fontWeight="bold",c.textContent=b?b+": ":"",g.appendChild(c));a&&(a=document.createTextNode(a),g.appendChild(a));f&&(g.addEventListener("mouseover",function(){g.style.cursor="pointer";g.style.borderWidth=
"1px 0 1px 0";g.style.borderColor="white";g.style.borderStyle="dashed"}),g.addEventListener("mouseout",function(){g.style.border="none"}),g.addEventListener("click",f));document.getElementById("conversation").appendChild(g);g.scrollIntoView()}
function help(){addMessage(" - - - - - Gun Game 2 - - - - - ","",!1,color(255),function(){window.open("https://hoangtran0410.github.io/GunGame2/index.html")});addMessage("Eat And Fight to Survive","",!1,color(150));addMessage("W A S D / ArrowKey: Move.");addMessage("LEFT-Mouse : Shoot.");addMessage("SCROLL-Mouse, 1->9 : Change Gun.");addMessage("R : Reload.");addMessage("F : Shield (can't shoot).");addMessage("Q (Hold): look around (minimap).");addMessage("M: Open/close minimap.");addMessage("N: Change music.");
addMessage("ENTER : Chat.");addMessage("C : Show/Hide Chat box.");addMessage("V : FreeCam Mode (on/off).");addMessage("Type '/help' for more option","",!1,color(200));addMessage("--------------------------------")}
function showChat(a){a?(document.getElementById("showHideChat").value="Hide",document.getElementById("conversation").style.width="100%",document.getElementById("chatBox").style.left="0px"):(document.getElementById("showHideChat").value="Show",document.getElementById("conversation").style.width="25%",document.getElementById("chatBox").style.left="-240px")}function isTyping(){return document.getElementById("inputMes")===document.activeElement}
function getPlayers(a,b,c,d){c=c||[];a=new Circle(a.x,a.y,b+maxSizeNow);d=d?quadPlayers.query(a,[],!0):quadPlayers.query(a);if(d.length&&c.length)for(c=$jscomp.makeIterator(c),a=c.next();!a.done;a=c.next())a=d.indexOf(a.value),-1!=a&&d.splice(a,1);return d}
function getItems(a,b,c,d){c=c||[];a=new Circle(a.x,a.y,b+maxSizeNow);d=d?quadItems.query(a,[],!0):quadItems.query(a);if(d.length&&c.length)for(c=$jscomp.makeIterator(c),a=c.next();!a.done;a=c.next())a=d.indexOf(a.value),-1!=a&&d.splice(a,1);return d}
function getBullets(a,b,c,d){c=c||[];a=new Circle(a.x,a.y,b+maxSizeNow);d=d?quadBulls.query(a,[],!0):quadBulls.query(a);if(d.length&&c.length)for(c=$jscomp.makeIterator(c),a=c.next();!a.done;a=c.next())a=d.indexOf(a.value),-1!=a&&d.splice(a,1);return d}function clone(a){if(null==a||"object"!=typeof a)return a;var b=a.constructor(),c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function getObjectIndex(a,b){var c=Object.keys(a).indexOf(b);-1==c&&(c=null);return c}
function getValueAtIndex(a,b){return Object.keys(a)[b]}function getObjectLength(a){return Object.keys(a).length}
window.onload=function(){setInterval(function(){gameTime=prettyTime(mil/1E3)},1E3);document.addEventListener("contextmenu",function(a){return a.preventDefault()});document.getElementById("resetBtn").addEventListener("click",function(a){a.target.style.display="none";document.getElementById("alert").style.opacity=0;document.getElementById("alert").style.zIndex=0;reset()});document.getElementById("closebtn").addEventListener("mouseover",function(a){a.target.parentElement.style.opacity=0;a.target.parentElement.style.zIndex=
0});document.getElementById("showHideChat").addEventListener("mouseover",function(a){"Hide"==a.target.value?showChat(!1):showChat(!0)})};function autoAddPortals(a,b,c){setInterval(function(){for(var b=0;b<a;b++){var f=new Portal("out",random(gmap.size.x),random(gmap.size.y),null,null,c),g=new Portal("in",random(gmap.size.x),random(gmap.size.y),f,null,c);pArr.push({inGate:g,outGate:f})}},1E3*b)}
function autoAddRedzones(a){setInterval(function(){redArr.push(new RedZone(random(gmap.size.x),random(gmap.size.y),random(150,gmap.size.x/8),random(15E3,6E4)))},1E3*a)}
function autoAddItems(a){setInterval(function(){if(iArr.length>maxItem)for(var a=0;a<iArr.length-maxItem;a++)iArr.shift();else if(iArr.length<maxItem/2)for(a=iArr.length;a<maxItem/2;a++)iArr.push(new Item(random(gmap.size.x),random(gmap.size.y)));for(a=0;5>a;a++)iArr.push(new Item(random(gmap.size.x),random(gmap.size.y)));a=floor(random(getObjectLength(weapons)));iArr.push(new Item(random(gmap.size.x),random(gmap.size.y),null,null,a))},1E3*a)}
function autoAddPlayers(a){setInterval(function(){if(eArr.length<maxE){var a=new Character(null,random(gmap.size.x),random(gmap.size.y));eArr.push(a)}},1E3*a)}function getMaxSizeNow(a){setInterval(function(){for(var a=p?p.radius:eArr[0].radius,c=$jscomp.makeIterator(eArr),d=c.next();!d.done;d=c.next())d=d.value,d.radius>a&&(a=d.radius);maxSizeNow=a},1E3*a)}
var myAudio,songNow,ampData,ampLevel,viewport,gmap,p,eArr=[],bArr=[],iArr=[],rArr=[],tArr=[],pArr=[],redArr=[],epArr=[],sArr=[],wArr=[],notifi=[],sound=[],pname,pcol,maxE=15,maxRock=50,maxTree=100,maxWater=4,quadPlayers,quadItems,quadBulls,boundMap,fr,mil=0,gameTime=0,maxItem=500,maxSizeNow=100,weaponInfo;
function setup(){createCanvas(windowWidth,windowHeight).position(0,0);noSmooth();rectMode(CENTER);textAlign(LEFT);textFont("Consolas");ampData=new p5.Amplitude;songNow=floor(random(musics.SongList.length));gmap=new GameMap(1E4,1E4,300);(pname=window.prompt("Enter your Player Name"))?localStorage.setItem("pname",pname):pname=localStorage.getItem("pname");reset();weaponInfo=new InfoWeapon;setInterval(function(){gmap.createMinimap()},1E4);boundMap=new Rectangle(gmap.size.x/2,gmap.size.y/2,gmap.size.x,
gmap.size.y);quadItems=new QuadTree(boundMap,5);quadBulls=new QuadTree(boundMap,5);quadPlayers=new QuadTree(boundMap,1);autoAddPlayers(5);autoAddItems(5);autoAddRedzones(30);getMaxSizeNow(2);autoAddPortals(2,15,14);help(10);changeSong(1);addAlertBox("Please read the Rules in chat box.","#f55","#fff")}
function draw(){if(focused){background(20);fr=frameRate();mil=millis();ampLevel=ampData.getLevel();viewport.run();push();translate(-viewport.pos.x+width/2,-viewport.pos.y+height/2);gmap.run();quadItems.clear();for(var a=$jscomp.makeIterator(iArr),b=a.next();!b.done;b=a.next())b=b.value,quadItems.insert(b);quadBulls.clear();a=$jscomp.makeIterator(bArr);for(b=a.next();!b.done;b=a.next())quadBulls.insert(b.value);quadPlayers.clear();p&&quadPlayers.insert(p);b=$jscomp.makeIterator(eArr);for(a=b.next();!a.done;a=
b.next())a=a.value,quadPlayers.insert(a);a=$jscomp.makeIterator(wArr);for(b=a.next();!b.done;b=a.next())b.value.run();for(b=iArr.length-1;0<=b;b--)iArr[b].run();for(b=bArr.length-1;0<=b;b--)bArr[b].run();for(b=rArr.length-1;0<=b;b--)rArr[b].run();p&&(p.move(),p.run());b=$jscomp.makeIterator(eArr);for(a=b.next();!a.done;a=b.next())a=a.value,a.autoMove(),a.autoFire(),a.run();p&&(p.hide=!1);b=$jscomp.makeIterator(eArr);for(a=b.next();!a.done;a=b.next())a=a.value,a.hide=!1;p&&mouseIsPressed&&"left"==
mouseButton&&p.fire(fakeToReal(mouseX,mouseY));keyIsDown(32)&&(viewport.pos=viewport.target.pos.copy());for(b=pArr.length-1;0<=b;b--)!pArr[b].inGate.run()&&pArr[b].outGate&&pArr[b].outGate.run();for(b=tArr.length-1;0<=b;b--)tArr[b].run();for(b=sArr.length-1;0<=b;b--)sArr[b].show();for(b=redArr.length-1;0<=b;b--)redArr[b].show();for(b=epArr.length-1;0<=b;b--)epArr[b].show(),epArr[b].checkExplore(epArr);pop();a=$jscomp.makeIterator(notifi);for(b=a.next();!b.done;b=a.next())b.value.run();gmap.showMinimap();
weaponInfo.show();textSize(20);textAlign(LEFT);noStroke();fill(255,150);text("Fps: "+floor(frameRate()),5,20);text("Time: "+gameTime,5,45);text("Players: "+((p?1:0)+eArr.length),5,70);text("Killed: "+viewport.target.killed,5,95);textAlign(CENTER);text(floor(viewport.pos.x)+" "+floor(viewport.pos.y),width/2,height-25)}}
function keyPressed(){if(!isTyping())if(86==keyCode)viewport.follow=!viewport.follow;else if(77==keyCode)gmap.hiddenMinimap=!gmap.hiddenMinimap;else if(70==keyCode)p&&(p.shield=!p.shield);else if(49<=keyCode&&57>=keyCode){if(p&&keyCode-49<p.weaponBox.length){var a=p.weaponBox.indexOf(getObjectIndex(weapons,p.weapon.name));p.changeWeapon(keyCode-49-a)}}else 82==keyCode?p&&p.weapon.gun.reload():67==keyCode?"Show"==document.getElementById("showHideChat").value?showChat(!0):showChat(!1):78==keyCode?changeSong(1):
72==keyCode?help(5):13==keyCode&&(showChat(!0),document.getElementById("inputMes").focus());else if(13==keyCode){a=document.getElementById("inputMes");switch(a.value){case "":break;case "/help":addMessage("/howtoplay, /showplayers, /clear, /reset, /contact","Server");break;case "/howtoplay":help();break;case "/showplayers":for(var b="",c=0;c<e.length;c++)b+=e[c].name+", ";addMessage(b,"Server",!1,color(0));break;case "/clear":for(b=document.getElementById("conversation");b.firstChild;)b.removeChild(b.firstChild);
break;case "/reset":reset();addMessage("The Game has been Restarted","Server",!0,color(0,150,0));break;case "/contact":addMessage("click here \u2665","My Github",!1,color(100),function(){window.open("https://github.com/HoangTran0410")});addMessage("click here \u2665","My Facebook",!1,color(0,0,255),function(){window.open("https://www.facebook.com/people/Hoang-Tran/100004848287494")});break;default:addMessage(event.target.value,pname,!0,color(pcol[0],pcol[1],pcol[2]))}a.blur();a.value=""}}
function mousePressed(){if(!p&&(event.target.matches("canvas")||"Show"==document.getElementById("showHideChat").value)){var a=eArr[(eArr.indexOf(viewport.target)+1)%eArr.length];viewport.target=a}}function mouseWheel(a){!p||!a.target.matches("canvas")&&"Show"!=document.getElementById("showHideChat").value||p.shield||(p.changeWeapon(0<a.delta?1:-1),addSound("audio/gun_switch_01.mp3",!1,.7))}
function windowResized(){resizeCanvas(windowWidth,windowHeight,!0);gmap.offSetX=width-gmap.minimapSize-10;weaponInfo=new InfoWeapon};